DROP TABLE TB_YOUTUBER CASCADE CONSTRAINTS;
DROP TABLE TB_MANAGER CASCADE CONSTRAINTS;
DROP TABLE TB_GRADE CASCADE CONSTRAINTS;
DROP SEQUENCE YTB_SEQ;


CREATE TABLE TB_YOUTUBER (
 YOUTUBER_CODE          NUMBER(10) PRIMARY KEY ,
 YOUTUBER_USERNAME      VARCHAR2(30) UNIQUE NOT NULL ,
 --YOUTUBER_NAME          VARCHAR2(30) NOT NULL ,
 YOUTUBER_NUMBER       VARCHAR2(30) UNIQUE NOT NULL,
 YOUTUBER_URL           VARCHAR2(150) NOT NULL, 
 GRADE_CODE             NUMBER(2),
 MANAGER_CODE           NUMBER(10),
 DEAL_YN                CHAR(1) DEFAULT 'Y'
);
COMMENT ON COLUMN TB_YOUTUBER.YOUTUBER_CODE  IS '유튜버 관리코드';
COMMENT ON COLUMN TB_YOUTUBER.YOUTUBER_USERNAME  IS '유튜버 계정이름';
--COMMENT ON COLUMN TB_YOUTUBER.YOUTUBER_NAME  IS '유튜버 이름';
COMMENT ON COLUMN TB_YOUTUBER.YOUTUBER_NUMBER  IS '유튜버 전화번호';
COMMENT ON COLUMN TB_YOUTUBER.YOUTUBER_URL  IS '사이트';
COMMENT ON COLUMN TB_YOUTUBER.GRADE_CODE  IS '등급 코드';
COMMENT ON COLUMN TB_YOUTUBER.MANAGER_CODE  IS '매니저 코드';
COMMENT ON COLUMN TB_YOUTUBER.DEAL_YN  IS '거래 여부';

CREATE SEQUENCE YTB_SEQ --시퀀스이름 WDRL_SEQ
 INCREMENT BY 1 --증감숫자 1
 START WITH 1
 MINVALUE 1
 MAXVALUE 1000
 NOCYCLE
 NOCACHE;

 
 
CREATE TABLE TB_MANAGER (
 MANAGER_CODE     NUMBER(2) PRIMARY KEY,
 MANAGER_NAME     VARCHAR2 (30) NOT NULL,
 MANAGER_NUMBER   VARCHAR2 (30) NOT NULL ); 
COMMENT ON COLUMN TB_MANAGER.MANAGER_CODE  IS '매니저 코드';
COMMENT ON COLUMN TB_MANAGER.MANAGER_NAME  IS '매니저 이름';
COMMENT ON COLUMN TB_MANAGER.MANAGER_NUMBER  IS '매니저 전화번호';


CREATE TABLE TB_GRADE (
 GRADE_CODE   NUMBER(2) PRIMARY KEY ,
 GRADE_NAME   VARCHAR2(15) NOT NULL);
COMMENT ON COLUMN TB_GRADE.GRADE_CODE  IS '등급 번호';
COMMENT ON COLUMN TB_GRADE.GRADE_NAME  IS '등급 이름';

ALTER TABLE TB_YOUTUBER
  ADD CONSTRAINT FK_YOUTUBER_CODE_01 FOREIGN KEY (GRADE_CODE)
  REFERENCES TB_GRADE (GRADE_CODE);


ALTER TABLE TB_YOUTUBER DISABLE CONSTRAINT FK_YOUTUBER_CODE_01;

--SELECT YTB_SEQ.NEXTVAL
--  FROM DUAL;

INSERT INTO TB_YOUTUBER (YOUTUBER_CODE, YOUTUBER_USERNAME, YOUTUBER_NUMBER, YOUTUBER_URL, GRADE_CODE,MANAGER_CODE,DEAL_YN) 
VALUES ( YTB_SEQ.NEXTVAL,
        '개발바댁', 
        '010-0000-0001', 
        'https://www.youtube.com/@devbadak',
        4,
        1,
        'Y'
);
INSERT INTO TB_YOUTUBER (YOUTUBER_CODE, YOUTUBER_USERNAME, YOUTUBER_NUMBER,YOUTUBER_URL,GRADE_CODE,MANAGER_CODE,DEAL_YN) 
VALUES ( YTB_SEQ.NEXTVAL,
        '니꼴라스형', 
        '010-0000-0002', 
        'https://www.youtube.com/@nomadcoders/about',
        2,
        2,
        'Y');

INSERT INTO TB_MANAGER (MANAGER_CODE, MANAGER_NAME, MANAGER_NUMBER) 
VALUES (1,
        '김야무짐', 
        '010-2000-0001');
INSERT INTO TB_MANAGER (MANAGER_CODE, MANAGER_NAME, MANAGER_NUMBER) 
VALUES (2,
        '권길동', 
        '010-3000-0001');

INSERT INTO TB_GRADE (GRADE_CODE, GRADE_NAME) VALUES (1,'브론즈');
INSERT INTO TB_GRADE (GRADE_CODE, GRADE_NAME) VALUES (2,'실버');
INSERT INTO TB_GRADE (GRADE_CODE, GRADE_NAME) VALUES (3,'골드');
INSERT INTO TB_GRADE (GRADE_CODE, GRADE_NAME) VALUES (4,'다이아몬드');
INSERT INTO TB_GRADE (GRADE_CODE, GRADE_NAME) VALUES (5,'루비');

COMMIT;

ALTER TABLE TB_YOUTUBER ENABLE CONSTRAINT FK_YOUTUBER_CODE_01;

COMMIT;